fix: minor fixes to cicd

diff --git a/.github/workflows/cicd_yt.yaml b/.github/workflows/cicd_yt.yaml
--- a/.github/workflows/cicd_yt.yaml
+++ b/.github/workflows/cicd_yt.yaml
@@ -4,7 +4,7 @@ on:
   push:
     branches:
       - master
-      - 'feature/*'
+      - "feature/*"
 
   pull_request:
     branches:
@@ -13,6 +13,7 @@ on:
   workflow_dispatch:
 
 jobs:
+
   build-and-push-image:
     runs-on: ubuntu-latest
 
@@ -44,66 +45,107 @@ jobs:
       - name: Build and push Docker image
         if: steps.changed-files-build.outputs.any_changed == 'true'
         run: |
-          docker buildx build --push \
+          docker buildx build \
+            --push \
             --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest \
             --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ github.sha }} \
             .
 
   unit-and-integration-and-e2e-tests:
     runs-on: ubuntu-latest
-    
+
     needs: build-and-push-image
-    
+
     env:
       AIRFLOW_WWW_USER_PASSWORD: ${{ secrets.AIRFLOW_WWW_USER_PASSWORD }}
       AIRFLOW_WWW_USER_USERNAME: ${{ secrets.AIRFLOW_WWW_USER_USERNAME }}
+
       API_KEY: ${{ secrets.API_KEY }}
+
       CELERY_BACKEND_NAME: ${{ secrets.CELERY_BACKEND_NAME }}
       CELERY_BACKEND_PASSWORD: ${{ secrets.CELERY_BACKEND_PASSWORD }}
       CELERY_BACKEND_USERNAME: ${{ secrets.CELERY_BACKEND_USERNAME }}
+
       ELT_DATABASE_NAME: ${{ secrets.ELT_DATABASE_NAME }}
       ELT_DATABASE_PASSWORD: ${{ secrets.ELT_DATABASE_PASSWORD }}
       ELT_DATABASE_USERNAME: ${{ secrets.ELT_DATABASE_USERNAME }}
+
       FERNET_KEY: ${{ secrets.FERNET_KEY }}
+
       METADATA_DATABASE_NAME: ${{ secrets.METADATA_DATABASE_NAME }}
       METADATA_DATABASE_PASSWORD: ${{ secrets.METADATA_DATABASE_PASSWORD }}
       METADATA_DATABASE_USERNAME: ${{ secrets.METADATA_DATABASE_USERNAME }}
+
       POSTGRES_USER: ${{ secrets.POSTGRES_CONN_USERNAME }}
       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_CONN_PASSWORD }}
+
       POSTGRES_CONN_HOST: ${{ secrets.POSTGRES_CONN_HOST }}
       POSTGRES_CONN_PASSWORD: ${{ secrets.POSTGRES_CONN_PASSWORD }}
       POSTGRES_CONN_PORT: ${{ secrets.POSTGRES_CONN_PORT }}
       POSTGRES_CONN_USERNAME: ${{ secrets.POSTGRES_CONN_USERNAME }}
+
       AIRFLOW_UID: ${{ vars.AIRFLOW_UID }}
+
       CHANNEL_HANDLE: ${{ vars.CHANNEL_HANDLE }}
+
       DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
       DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
       DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
-    
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
       - name: Get changed files
-        id: changed-files-build
+        id: changed-files-tests
         uses: tj-actions/changed-files@v45
         with:
           files: |
             dags/**
             include/**
             docker-compose.yaml
-      - name: Set up Docker compose
-        if: steps.changed-files-tests.output.any_changed == 'true'
+            tests/**
+
+      - name: Set up Docker Compose
+        if: steps.changed-files-tests.outputs.any_changed == 'true'
         run: docker compose up -d
+
+      # - name: Wait for Airflow container
+      #   if: steps.changed-files-tests.outputs.any_changed == 'true'
+      #   run: |
+      #     echo "Waiting for Airflow services..."
+
+      #     for i in {1..30}; do
+      #       if docker compose exec -T airflow-worker airflow version; then
+      #         echo "Airflow is ready!"
+      #         exit 0
+      #       fi
+
+      #       echo "Still waiting..."
+      #       sleep 10
+      #     done
+
+      #     echo "Airflow failed to start"
+      #     exit 1
+
       - name: Run Unit and Integration Tests
-        if: steps.changed-files-tests.output.any_changed == 'true'
-        run: docker exec -t airflow-worker sh -c "pytest tests/ -v"
-      - name: Run End-to-End Dag Tests
-        if: steps.changed-files-tests.output.any_changed == 'true'
-        run:  |
-          DAG_NAMES={"produce_json" "update_db" "data_quality"}
+        if: steps.changed-files-tests.outputs.any_changed == 'true'
+        run: |
+          docker compose exec -T airflow-worker \
+            pytest tests/ -v
+
+      - name: Run End-to-End DAG Tests
+        if: steps.changed-files-tests.outputs.any_changed == 'true'
+        run: |
+          DAG_NAMES=("produce_json" "update_db" "data_quality")
+
           for DAG in "${DAG_NAMES[@]}"; do
-            docker exec -t airflow-worker sh -c "airflow dags test DAG"
+            echo "Testing DAG: $DAG"
+
+            docker compose exec -T airflow-worker \
+              airflow dags test "$DAG"
           done
+
       - name: Tear down Docker Compose
-        if: steps.changed-files-tests.output.any_changed == 'true'
+        if: always() && steps.changed-files-tests.outputs.any_changed == 'true'
         run: docker compose down
